variables:
  DOCKER_DRIVER: overlay2

  DIST_IMAGE_LATEST: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:latest"
  DIST_IMAGE_SHA: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA"
  DIST_IMAGE_SHA_BEFORE: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_BEFORE_SHA"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - mkdir empty_dir

image: docker:latest

services:
  - docker:dind

stages:
  - build

build:
  stage: build
  tags:
    - docker
  script:
    - docker pull $DIST_IMAGE_LATEST || true
    - docker pull $DIST_IMAGE_SHA || true
    - docker pull $DIST_IMAGE_SHA_BEFORE || true
    - docker build --pull --cache-from $DIST_IMAGE_LATEST --cache-from $DIST_IMAGE_SHA_BEFORE --cache-from DIST_IMAGE_SHA --tag $DIST_IMAGE_SHA --tag $DIST_IMAGE_LATEST empty_dir
    - docker push $DIST_IMAGE_LATEST
    - docker push $DIST_IMAGE_SHA
